import type { Config } from "tailwindcss";
import animatePlugin from "tailwindcss-animate";

const config: Config = {
    darkMode: "class",
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                grin: {
                    50: "var(--color-grin-50)",
                    100: "var(--color-grin-100)",
                    200: "var(--color-grin-200)",
                    300: "var(--color-grin-300)",
                    400: "var(--color-grin-400)",
                    500: "var(--color-grin-500)",
                    600: "var(--color-grin-600)",
                    700: "var(--color-grin-700)",
                    800: "var(--color-grin-800)",
                    900: "var(--color-grin-900)",
                    950: "var(--color-grin-950)",
                    DEFAULT: "var(--color-grin-500)",
                },
                peenk: {
                    50: "var(--color-peenk-50)",
                    100: "var(--color-peenk-100)",
                    200: "var(--color-peenk-200)",
                    300: "var(--color-peenk-300)",
                    400: "var(--color-peenk-400)",
                    500: "var(--color-peenk-500)",
                    600: "var(--color-peenk-600)",
                    700: "var(--color-peenk-700)",
                    800: "var(--color-peenk-800)",
                    900: "var(--color-peenk-900)",
                    950: "var(--color-peenk-950)",
                    DEFAULT: "var(--color-peenk-500)",
                },
                ohrange: {
                    50: "var(--color-ohrange-50)",
                    100: "var(--color-ohrange-100)",
                    200: "var(--color-ohrange-200)",
                    300: "var(--color-ohrange-300)",
                    400: "var(--color-ohrange-400)",
                    500: "var(--color-ohrange-500)",
                    600: "var(--color-ohrange-600)",
                    700: "var(--color-ohrange-700)",
                    800: "var(--color-ohrange-800)",
                    900: "var(--color-ohrange-900)",
                    950: "var(--color-ohrange-950)",
                    DEFAULT: "var(--color-ohrange-500)",
                },
                perple: {
                    50: "var(--color-perple-50)",
                    100: "var(--color-perple-100)",
                    200: "var(--color-perple-200)",
                    300: "var(--color-perple-300)",
                    400: "var(--color-perple-400)",
                    500: "var(--color-perple-500)",
                    600: "var(--color-perple-600)",
                    700: "var(--color-perple-700)",
                    800: "var(--color-perple-800)",
                    900: "var(--color-perple-900)",
                    950: "var(--color-perple-950)",
                    DEFAULT: "var(--color-perple-500)",
                },
                lermorn: {
                    50: "var(--color-lermorn-50)",
                    100: "var(--color-lermorn-100)",
                    200: "var(--color-lermorn-200)",
                    300: "var(--color-lermorn-300)",
                    400: "var(--color-lermorn-400)",
                    500: "var(--color-lermorn-500)",
                    600: "var(--color-lermorn-600)",
                    700: "var(--color-lermorn-700)",
                    800: "var(--color-lermorn-800)",
                    900: "var(--color-lermorn-900)",
                    950: "var(--color-lermorn-950)",
                    DEFAULT: "var(--color-lermorn-500)",
                },
            },
            fontFamily: {
                sans: ["var(--font-axiforma)", "system-ui", "sans-serif"],
                heading: ["var(--font-clash-display)", "system-ui", "sans-serif"],
                handwriting: ["var(--font-gochi-hand)", "cursive"],
            },
        },
    },
    plugins: [animatePlugin],
};

export default config;
